version: '3.9'

services:
  auth_service:
    build:
      context: .
    env_file:
      - ./.env.test
    ports:
      - "81:81"
    depends_on:
      - auth_db
    command: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 81"
  auth_db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=pastebin_authentication_service
  pastebin_nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - auth_service
volumes:
  postgres_data: